---
title: "analisis crimen"
author: "John Esteban"
date: "2024-04-29"
output: html_document
---

```{r}
library(sf)
library(tidyverse)
```

```{r}
shp_data <- st_read("crimen/DAILoc.shp")
shp_df <- st_read("crimen/DAILoc.dbf")
data <- read.csv('train_join2.csv')
data_t <- read.csv('test_join2.csv')
```
 # Se transforman los datos en formato espacial 
 
```{r}
train <- st_as_sf(data,coords=c('Lon','Lat'),crs=4326)
train<-st_transform(train,4686)

test <- st_as_sf(data_t,coords=c('lon','lat'),crs=4326)
test<-st_transform(test,4686)


shp_data <- st_as_sf(shp_data,coords='geometry',crs=4326)
shp_data<-st_transform(shp_data,4686)
```






#### Robos

```{r}
hurtos_vivienda <- grep("HR", names(shp_data), value = TRUE)
hurtos_vivienda <- shp_data[, hurtos_vivienda]
hurtos_vivienda <- hurtos_vivienda %>% select(CMHR21CONT)
hurtos_vivienda
```

```{r}
hurtos_personas <- grep("HP", names(shp_data), value = TRUE)
hurtos_personas <- shp_data[, hurtos_personas]
hurtos_personas <- hurtos_personas %>% select(CMHP21CONT)
hurtos_personas
```

```{r}
matriz_dist_hv<-st_distance(hurtos_vivienda,train)
matriz_dist_hp<-st_distance(hurtos_personas,train)

matriz_dist_hv<-st_distance(hurtos_vivienda,test)
matriz_dist_hp<-st_distance(hurtos_personas,test)
```





```{r}
distancia_minima_hv <- apply(matriz_dist_hv, 2, function(row) {
  min_dist <- min(row, na.rm = TRUE)
  min_index <- which.min(row)
  return(c(valor_minimo = min_dist, valor_primera_columna = hurtos_vivienda[min_index, 1]))
})

distancia_minima_hv_df <- t(sapply(distancia_minima_hv, unlist))

robos_vivienda <- list()
for (i in seq_len(nrow(train))) {
  valor_robos_vivienda <- distancia_minima_hv[[i]][[2]]
  robos_vivienda[[i]] <- valor_robos_vivienda
}
robos_vivienda_df <-do.call(rbind, robos_vivienda)
robos_vivienda_df <- as.data.frame(robos_vivienda_df)
colnames(robos_vivienda_df) <-'Robos_vivienda'

####################### Robos personas
distancia_minima_hp <- apply(matriz_dist_hp, 2, function(row) {
  min_dist <- min(row, na.rm = TRUE)
  min_index <- which.min(row)
  return(c(valor_minimo = min_dist, valor_primera_columna = hurtos_personas[min_index, 1]))
})

distancia_minima_hp_df <- t(sapply(distancia_minima_hp, unlist))

robos_personas <- list()
for (i in seq_len(nrow(train))) {
  valor_robos_personas<- distancia_minima_hp[[i]][[2]]
  robos_personas[[i]] <- valor_robos_personas
}
robos_personas_df <-do.call(rbind, robos_personas)
robos_personas_df <- as.data.frame(robos_personas_df)
colnames(robos_personas_df) <-'Robos_personas'
```

```{r}
distancia_minima_hv <- apply(matriz_dist_hv, 2, function(row) {
  min_dist <- min(row, na.rm = TRUE)
  min_index <- which.min(row)
  return(c(valor_minimo = min_dist, valor_primera_columna = hurtos_vivienda[min_index, 1]))
})

distancia_minima_hv_df <- t(sapply(distancia_minima_hv, unlist))

robos_vivienda <- list()
for (i in seq_len(nrow(test))) {
  valor_robos_vivienda <- distancia_minima_hv[[i]][[2]]
  robos_vivienda[[i]] <- valor_robos_vivienda
}
robos_vivienda_df <-do.call(rbind, robos_vivienda)
robos_vivienda_df <- as.data.frame(robos_vivienda_df)
colnames(robos_vivienda_df) <-'Robos_vivienda'

####################### Robos personas
distancia_minima_hp <- apply(matriz_dist_hp, 2, function(row) {
  min_dist <- min(row, na.rm = TRUE)
  min_index <- which.min(row)
  return(c(valor_minimo = min_dist, valor_primera_columna = hurtos_personas[min_index, 1]))
})

distancia_minima_hp_df <- t(sapply(distancia_minima_hp, unlist))

robos_personas <- list()
for (i in seq_len(nrow(test))) {
  valor_robos_personas<- distancia_minima_hp[[i]][[2]]
  robos_personas[[i]] <- valor_robos_personas
}
robos_personas_df <-do.call(rbind, robos_personas)
robos_personas_df <- as.data.frame(robos_personas_df)
colnames(robos_personas_df) <-'Robos_personas'
```




```{r}
train <-cbind.data.frame(train,robos_vivienda_df,robos_personas_df)
```


```{r}
test <-cbind.data.frame(test,robos_vivienda_df,robos_personas_df)
```

```{r}
test %>%
  select(price,Robos_vivienda,Robos_personas) %>%
  cor()
```

```{r}

```







### POlicia


```{r}
robos_test <- test %>% select(Robos_vivienda,Robos_personas)
```


```{r}
require("pacman")
p_load("osmdata")
```



```{r}
bogota<-opq(bbox = getbb("Bogota Colombia"))
seguridad<- bogota %>% 
                add_osm_feature(key="amenity",value="police") %>% 
  osmdata_sf()
seguridad<-seguridad$osm_point
```


```{r}

seguridad <- st_as_sf(seguridad,coords='geometry',crs=4326)
seguridad<-st_transform(seguridad,4686)
seguridad <- seguridad %>% select(osm_id,geometry)
```



```{r}
train <- st_as_sf(data,coords=c('Lon','Lat'),crs=4326)
train<-st_transform(train,4686)
train <- st_transform(train, st_crs(seguridad))
```

```{r}
test <- st_as_sf(data_t,coords=c('lon','lat'),crs=4326)
test<-st_transform(test,4686)
test <- st_transform(test, st_crs(seguridad))
```

```{r}
matriz_dist<-st_distance(seguridad,test)
distancia_minima <- apply(matriz_dist, 2, min, na.rm = TRUE)
test <- test %>% 
  mutate(distancia_estacion_policia = distancia_minima)
```

```{r}
test_en <- as.data.frame(test)
test_en %>%
  select(price,distancia_estacion_policia) %>%
  cor
```

```{r}
matriz_dist<-st_distance(seguridad,train)
distancia_minima <- apply(matriz_dist, 2, min, na.rm = TRUE)
train <- train %>% 
  mutate(distancia_estacion_policia = distancia_minima)
```




```{r}
train_en <- as.data.frame(train)
train_en %>%
  select(price,distancia_estacion_policia) %>%
  cor
```




```{r}
robos <- train %>% select(Robos_vivienda,Robos_personas,distancia_estacion_policia)

write.csv(robos,'seguridad.csv')
```


##### Test

```{r}
robos_test_2<- test %>% select(distancia_estacion_policia)
robos_test <- cbind.data.frame(robos_test,robos_test_2)

write.csv(robos_test,'seguridad_test.csv')
```











