---
title: "Taller_3"
author: "John Esteban"
date: "2024-04-27"
output: html_document
bibliography: bibliografia.bib
---

# Entorno

```{r}
data <- read.csv('train_join.csv')
```

# Introduccion

La inversión más importante para la mayoría de las personas es tener casa propia, y esta es una de las fuentes más comunes en la acumulación de capital. Por esto, conocer cuáles son los elementos que determinan el valor de este bien puede servir de guía para el proceso de planificación financiera.

Para la determinación de los precios de las viviendas, en la literatura se han logrado avances significativos. Primero, en relación a las variables, donde los principales trabajos se han concentrado en utilizar las características propias del hogar, con menor impacto de las características externas al hogar aparte del lugar donde están ubicadas. Luego, en relación a los modelos utilizados, se usan los principales algoritmos como regresión lineal, que ayuda en la interpretación, pero también todos los algoritmos basados en árboles de decisión.

Para la selección de variables, se han tomado varias alternativas clasificadas en 3 grupos: características propias del hogar y características del entorno donde está ubicado el hogar. Las más importantes o que más aportan para determinar el precio de la vivienda son: el número de habitaciones, el área del hogar, planta, cantidad de baños, si tiene garaje, edad de la propiedad, área construida, aire acondicionado y el estrato de la vivienda. Los trabajos llegan a la conclusión de que las mejores variables para explicar el precio son: número de habitaciones y de baños, junto con área construida y el estrato.

El segundo grupo de variables está relacionado con las características del entorno donde está ubicada la vivienda. Se utilizan variables como la distancia a estaciones de transporte y de educación, proporción de personas de bajos recursos que viven cerca, porcentaje de centros de negocio y la localización. La distancia al transporte es la característica que más peso tiene.

El modelo que mejor rendimiento ha presentado para la predicción de los precios es el Random Forest. El trabajo desarrollado por @Cueto2022, utilizando solo características de la vivienda en 5 modelos, entre ellos redes neuronales y modelos basados en árboles, encuentra que el que tiene mejor rendimiento es el random forest. De la misma forma, el trabajo de @Choy2023, en donde, además de las características, se utiliza la variable de la distancia al transporte, encuentra que el mejor modelo es el random forest. @Navarro2020, @Alzate2019 y @Angie también encuentran que el random forest es el mejor modelo.

Sin embargo, hay otros algoritmos que también han tenido buen desempeño para predecir el precio de las viviendas. En el trabajo de @Mohamed2023, se destaca el uso de redes neuronales. @Bushan2010 sugiere trabajar con XGBoost, mientras que el modelo Ripper mostró un rendimiento destacado en el trabajo de @Park2015. Además, tanto el gradient boosting como el random forest demostraron eficacia en el estudio de @Alzate2019.

El propósito de este artículo es realizar la predicción de precios de vivienda en Bogotá. En este proceso, se utilizan variables propias de la vivienda, pero en la misma medida, variables que describan el entorno donde está ubicada la vivienda, y también se hace uso extensivo de las técnicas de procesamiento de lenguaje que permiten aprovechar las descripciones de la vivienda.

# Data

## Agregacion de las nuevas variables

Para modelar el precio de las viviendas en Bogota en primer lugar se cuenta con las caracteristicas propias del hogar. En primer lugar tenemos el precio de la vivienda que es la variable que se va a modelar y luego algunos atributos escensiales para iniciar con el proceso de modelacion. Como es el area que tiene la vivienda , el numero de habitaciones de habitaciones para dormir y de banos. Tambien es posible caracterizar el tipo de vivienda si es casa o apartamento. Y luego tambien se tiene a disposicion la descripcion de la vivienda de donde se pueden tomar datos que ayuden a describir mejor la vivienda.

Para conocer mejor el contexto en el que se ubica la vivienda , se crea la variable estrato a partir de la informacion del dane. ( William debe ampliar la explicacion)

La percepcion de seguridad es tambien un aspecto clave para determinanr la dispocion a pagar por una casa. Se espera que si hay mayor seguridad entonces el precio de la vivienda sea mayor. Para esto se incluyeron una serie de variables que pueden ayudar a medir este fenomeno. Con las cifras oficiales de la alcaldia se trajeron informacion geolocalizada de hurtos a personas y viviendas, la informacion solo esta disponible a traves de localidades no georeferenciada en forma similar a la base de datos, para esto por medio de la distnacia se trae la informacion de hurtos mas cercanas. Ademas tambien por medio de  la informacion de google se trae la distnacia que existen entre las viviendas y las estaciones de policia.


























